### ISSUE TITLE
config에 projects/example.yaml라는 부분이 있음

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-restbase#1]
https://github.com/femiwiki/restbase/blob/e5b738553a7a0ed79d04bed84337e877c1452d80/config.yaml#L32

작동은 잘 하는데 매우 고쳐야 할 거 같이 생겼습니다.

**Comment by simnalamburt** [comment]
문서를 찾을 수 없어서 어떻게 고쳐야하는건지 모르겠음. 작동은 잘 하니 그냥 둠

**Comment by lens0021** [comment]
1.1.1에서 삭제됐습니다.
https://github.com/wikimedia/restbase/commit/5cdd0051cf316a3109ab5d4d79786fa2e0cafe3b
